version: "3"
services:

  #web page for my portfolio
  react-web-page:
    build:
      context: ./my-portfolio-web-page
      dockerfile: Dockerfile
      args:
        - PROJECT_URL_ONE=http://viket.ryuichi24.com/
        - PROJECT_URL_TWO=http://tible.ryuichi24.com/
    image: ryuichi24/react-web-page:latest
    restart: always
    ports:
      - 3000:88


  #video link manager
  react-app-1:
    build:
      context: ./video-link-manager
      dockerfile: Dockerfile
      args:
        - API_URL=http://ryuichi24.com:89/video-link-manager
    image: ryuichi24/react-viket:latest
    restart: always
    ports:
      - 3010:81

  #flask api for video link manager
  flask:
    image: ryuichi24/flask-api-video-link-manager:latest
    restart: always
    container_name: flask
    environment:
      SECRET_KEY: love-programming
      JWT_SECRET_KEY: love-programming-jwt
      DATABASE_URL: mysql+pymysql://ryuichi:love-programming@mysql/ryuichiDb
      CLIENT_ORIGIN: '*'
    command: /bin/sh -c "./boot.sh"
    ports:
      - 5001:5000


  #time table manager
  react-app-2:
    build:
      context: ./time-table-manager
      dockerfile: Dockerfile
      args:
        - API_URL=http://ryuichi24.com:89/time-table-manager
    image: ryuichi24/react-time-table-manager:latest
    restart: always
    ports:
      - 3020:82

  #express api for time table manager
  express:
    image: ryuichi24/express-api-time-table-manager
    restart: always
    container_name: express
    environment:
      PORT: 5010
      DB_PASS: love-programming
      DB_USER: ryuichi
      MYSQL_DB: ryuichiDb
      DB_HOST: mysql
      DB_PORT: 3306
      JWT_KEY: love-programming
      CLIENT_ORIGIN: '*'
    ports:
      - 5002:5010


  #MySQL database
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql-auth.cnf:/etc/mysql/conf.d/mysql-auth.cnf
      - ./time-table-manager.sql:/docker-entrypoint-initdb.d/time-table-manager.sql
    environment:
      MYSQL_ROOT_PASSWORD: love-programming
      MYSQL_DATABASE: ryuichiDb
      MYSQL_USER: ryuichi
      MYSQL_PASSWORD: love-programming


  nginx-api:
    image: nginx:alpine
    restart: always
    container_name: nginx-api
    ports:
      - 89:89
    volumes:
      - ./nginx-api/nginx-reverse-api.conf:/etc/nginx/conf.d/default.conf


  nginx-front:
    image: nginx:alpine
    restart: always
    container_name: nginx-front
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-front:/etc/nginx/conf.d